language: python
python:
    - "2.7"
install:
    - sudo apt-get update -qq
    - sudo apt-get install -y python-dev libfreetype6-dev libpng12-dev libhdf5-serial-dev libblas-dev liblapack-dev gfortran python-tk tk-dev libsqlite3-dev libbz2-dev python-bsddb3-dbg libgdbm-dev libreadline-dev libffi-dev
    - wget https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz -O /tmp/python2.7.10.tgz
    - tar -xzf /tmp/python2.7.10.tgz
    - cd ./Python2.7.10 && ./configure && make && sudo make install
    - echo python --version
    - pip install --upgrade .
script:
    - make test
